server:
  port: 8988

logging:
  level:
    web: debug
    sql: debug

spring:
  data:
    mongodb:
      host: ${NOSQL_DB_IP:localhost}
      port: ${NOSQL_DB_PORT:27017}
      database: ${NOSQL_DB_NAME:courier_tracking}
      username: ${NOSQL_DB_USERNAME:courier_tracking}
      password: ${NOSQL_DB_PASSWORD:courier_tracking_pass}
